---
- name: Gather UniFi AP Configuration
  hosts: all
  gather_facts: false
  tasks:
    - name: Get current configuration
      raw: cat /tmp/system.cfg
      register: ap_config

    - name: Display configuration
      debug:
        msg: "{{ ap_config.stdout_lines }}"

    - name: Save configuration to file
      copy:
        content: "{{ ap_config.stdout }}"
        dest: "logs/unifi_{{ inventory_hostname }}_config.cfg"
      delegate_to: localhost
