#!/bin/bash
# Production Migration Script for Security Implementation
#
# This script migrates an existing ansible-simpleweb installation to the
# new security-enabled version. Run this AFTER verifying your backup.
#
# Usage:
#   ./scripts/migrate_production.sh [--dry-run] [--skip-backup-check]
#
# Prerequisites:
#   1. Run scripts/backup_environment.sh first
#   2. Verify backup can be restored (test in separate directory)
#   3. Set required environment variables (see below)
#
# Required Environment Variables:
#   INITIAL_ADMIN_PASSWORD - Password for the admin user
#   MONGO_PASSWORD - MongoDB admin password (if using MongoDB)
#
# Optional Environment Variables:
#   INITIAL_ADMIN_USER - Admin username (default: admin)
#   SSL_ENABLED - Enable SSL (default: true)
#   SSL_MODE - Certificate mode: auto, provided, disabled (default: auto)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
DRY_RUN=false
SKIP_BACKUP_CHECK=false

for arg in "$@"; do
    case $arg in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --skip-backup-check)
            SKIP_BACKUP_CHECK=true
            shift
            ;;
    esac
done

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running from project root
if [ ! -f "docker-compose.yml" ]; then
    log_error "Please run this script from the project root directory"
    exit 1
fi

# Pre-flight checks
log_info "Running pre-flight checks..."

# Check for required environment variables
if [ -z "$INITIAL_ADMIN_PASSWORD" ]; then
    log_error "INITIAL_ADMIN_PASSWORD environment variable is required"
    log_info "Set it with: export INITIAL_ADMIN_PASSWORD='your-secure-password'"
    exit 1
fi

# Check password strength (basic check)
if [ ${#INITIAL_ADMIN_PASSWORD} -lt 12 ]; then
    log_warn "INITIAL_ADMIN_PASSWORD should be at least 12 characters for security"
fi

# Check for backup
if [ "$SKIP_BACKUP_CHECK" = false ]; then
    BACKUP_DIR=$(ls -td backups/pre-security-* 2>/dev/null | head -1)
    if [ -z "$BACKUP_DIR" ]; then
        log_error "No backup found in backups/ directory"
        log_info "Run scripts/backup_environment.sh first"
        exit 1
    fi
    log_info "Found backup: $BACKUP_DIR"
fi

# Check disk space
AVAILABLE_SPACE=$(df -m . | awk 'NR==2 {print $4}')
if [ "$AVAILABLE_SPACE" -lt 1000 ]; then
    log_warn "Low disk space: ${AVAILABLE_SPACE}MB available"
fi

# Check Docker is running
if ! docker info > /dev/null 2>&1; then
    log_error "Docker is not running"
    exit 1
fi

log_info "Pre-flight checks passed"

if [ "$DRY_RUN" = true ]; then
    log_info "=== DRY RUN MODE - No changes will be made ==="
fi

# Step 1: Create migration timestamp
MIGRATION_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
log_info "Migration timestamp: $MIGRATION_TIMESTAMP"

# Step 2: Stop services
log_info "Stopping services..."
if [ "$DRY_RUN" = false ]; then
    docker compose down
else
    log_info "[DRY RUN] Would run: docker compose down"
fi

# Step 3: Create pre-migration backup (additional safety)
log_info "Creating pre-migration backup..."
if [ "$DRY_RUN" = false ]; then
    mkdir -p "backups/pre-migration-$MIGRATION_TIMESTAMP"

    # Backup volumes if they exist
    for volume in mongodb_data; do
        if docker volume inspect "ansible-simpleweb_${volume}" > /dev/null 2>&1; then
            log_info "Backing up volume: $volume"
            docker run --rm \
                -v "ansible-simpleweb_${volume}:/data:ro" \
                -v "$(pwd)/backups/pre-migration-$MIGRATION_TIMESTAMP:/backup" \
                alpine tar czf "/backup/${volume}.tar.gz" -C /data . 2>/dev/null || true
        fi
    done

    # Backup config
    if [ -d "config" ]; then
        cp -r config "backups/pre-migration-$MIGRATION_TIMESTAMP/"
    fi

    log_info "Backup saved to: backups/pre-migration-$MIGRATION_TIMESTAMP"
else
    log_info "[DRY RUN] Would create backup in: backups/pre-migration-$MIGRATION_TIMESTAMP"
fi

# Step 4: Update environment file
log_info "Updating environment configuration..."
if [ "$DRY_RUN" = false ]; then
    # Create or update .env file
    cat > .env.security << EOF
# Security Configuration - Generated by migrate_production.sh
# Timestamp: $MIGRATION_TIMESTAMP

# Authentication
AUTH_ENABLED=true
INITIAL_ADMIN_USER=${INITIAL_ADMIN_USER:-admin}
INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}

# SSL/TLS
SSL_ENABLED=${SSL_ENABLED:-true}
SSL_MODE=${SSL_MODE:-auto}

# MongoDB (if applicable)
MONGO_PASSWORD=${MONGO_PASSWORD:-}

# Session
SESSION_TIMEOUT=${SESSION_TIMEOUT:-3600}
EOF

    log_info "Security environment file created: .env.security"
    log_info "Review and merge with your existing .env file"
else
    log_info "[DRY RUN] Would create .env.security file"
fi

# Step 5: Create certificates directory
log_info "Ensuring certificate directory exists..."
if [ "$DRY_RUN" = false ]; then
    mkdir -p config/certs
    chmod 700 config/certs
else
    log_info "[DRY RUN] Would create config/certs directory"
fi

# Step 6: Build new images
log_info "Building updated images..."
if [ "$DRY_RUN" = false ]; then
    docker compose build
else
    log_info "[DRY RUN] Would run: docker compose build"
fi

# Step 7: Start services
log_info "Starting services..."
if [ "$DRY_RUN" = false ]; then
    docker compose up -d
else
    log_info "[DRY RUN] Would run: docker compose up -d"
fi

# Step 8: Wait for services to be healthy
log_info "Waiting for services to be ready..."
if [ "$DRY_RUN" = false ]; then
    sleep 10

    # Check if web service is responding
    MAX_RETRIES=30
    RETRY_COUNT=0
    while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
        if curl -sf http://localhost:3001/health > /dev/null 2>&1; then
            log_info "Web service is healthy"
            break
        fi
        RETRY_COUNT=$((RETRY_COUNT + 1))
        sleep 2
    done

    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
        log_error "Web service did not become healthy in time"
        log_info "Check logs with: docker compose logs ansible-web"
        exit 1
    fi
else
    log_info "[DRY RUN] Would wait for services to be healthy"
fi

# Step 9: Verify migration
log_info "Verifying migration..."
if [ "$DRY_RUN" = false ]; then
    # Check services are running
    if docker compose ps | grep -q "Up"; then
        log_info "Services are running"
    else
        log_error "Some services are not running"
        docker compose ps
        exit 1
    fi

    # Check login page is accessible
    if curl -sf http://localhost:3001/login > /dev/null 2>&1; then
        log_info "Login page is accessible"
    else
        log_warn "Login page check failed - may need manual verification"
    fi
else
    log_info "[DRY RUN] Would verify services are running"
fi

# Summary
echo ""
echo "=========================================="
log_info "Migration completed successfully!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Merge .env.security into your .env file"
echo "2. Access the application at:"
echo "   - HTTP:  http://localhost:3001 (redirects to HTTPS)"
echo "   - HTTPS: https://localhost:3443"
echo "3. Login with:"
echo "   - Username: ${INITIAL_ADMIN_USER:-admin}"
echo "   - Password: (the password you set)"
echo "4. Review and test:"
echo "   - [ ] Login works correctly"
echo "   - [ ] Existing schedules are visible"
echo "   - [ ] Existing inventory is accessible"
echo "   - [ ] Workers can reconnect"
echo "   - [ ] Playbooks execute correctly"
echo ""
echo "If issues occur, rollback with:"
echo "  ./scripts/restore_environment.sh backups/pre-migration-$MIGRATION_TIMESTAMP"
echo ""
echo "Backup location: backups/pre-migration-$MIGRATION_TIMESTAMP"
